### PR TITLE
Closes #105: Set class on active notifications bar

### LINKED ISSUE #105: Add a class when notifications bar is visible instead of animating on height

### PR DESCRIPTION
**Pull request by CloudNiner**

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Might want to check the Navbar tests.

**Comment by CloudNiner** [comment]
Updated, tests fixed

**Comment by flibbertigibbet** [comment]
+1 from me, suppose @jfrankl should still take a look

**Comment by jfrankl** [comment]
+1! Exactly what I was looking for. Thanks Andrew.

On Tue, Feb 10, 2015 at 3:28 PM, Kathryn Killebrew <notifications@github.com

> wrote:
> 
> +1 from me, suppose @jfrankl https://github.com/jfrankl should still
> take a look
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/nih-wayfinding/pull/136#issuecomment-73777219.

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com

**Pull request merged**
