### PR TITLE
Add nice places geojson

### PR DESCRIPTION
**Pull request by CloudNiner**
- Converted with ogr2ogr @ http://ogre.adc4gis.com
- Verified geojson looks correct by uploading to geojson.io
- Loaded into app and displayed via console.log to verify
  correctness in the angular service
- Size is ~58k

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
+1

**Comment by flibbertigibbet** [comment]
I'm guessing we probably don't need most of the attributes on it (shape length?  grid code?) if size is an issue.

**Comment by CloudNiner** [comment]
Yeah, I'll likely remove them once the next task is done.

**Comment by jbranigan** [comment]
It doesn't matter for now, but grid code could be used to prioritize points. The higher the number, the nicer the place (theoretically). It was a default field name when converting from raster to shape...

**Comment by CloudNiner** [comment]
Ok good to know. Deleting these properties doesn't save much space, so I'm going to leave them on for now.

**Pull request merged**
